#!/bin/bash

#SBATCH -A emslc50414
#SBATCH -p pncc
#SBATCH -t 1:00:00
#SBATCH --gres=gpu:volta:2
#SBATCH -N 1
#SBATCH -e AutoMicroED.err
#SBATCH -o AutoMicroED.out
#SBATCH --mail-user=
#SBATCH --job-name=AutoMicroED

